// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("Index.html", "Indlela Group", "Copyright © 2020 BuddySoft Systems  This site Has been removed by BuddySoft  Please contact Byrone Malay    072 120 0628 info@buddysoft.co.za   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Log-a-Call.html", "Indlela Group Call Log", "Copyright © 2020 BuddySoft Systems  Share  Contact Us  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  If you have a Fault to report please continue with this form   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Risk.html", "Indlela Group Risk", "Contact Us  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  Copyright © 2020 BuddySoft Systems   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Construction.html", "Indlela Group Construction", "Projects  Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  To be the benchmark supplier of services on the African Continent by using our consultancy methodology and addressing key critical issues that are burdening the business bottom line   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Amend-debt.html", "Indlela Group Debt Collectors", "Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Communications.html", "Indlela Group Communications", "Contact Us  Indlela Group is working closely with some of the world’s best manufacturing companies and keeping our clients up to date with latest and best innovative technologies, committed to evolving daily production and securing your future    Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  NWET is an ICT company which strives for increased customer relations and work satisfaction Better industry service with leading technical knowledge to provide customers with the best known solution for their business practice  View More  Coverage Map  Full Network Setup and Maintenance   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Online-Store.html", "Indlela Group Online Store", "Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Security.html", "Indlela Group Security", "Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Finance.html", "Indlela Group Finance", "Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  T&C Apply All Loans and Rentals Are Subject to approval   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Property.html", "Indlela Group Property", "Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Careers.html", "Careers", "Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  Available Positions  1   Permanent Intermediate position  Klerksdorp Area  Market Related cost to company Neg  Ref JHB000531JN  Please send your CV and Certified Qualifications with position number to IndlelaGroupCareers@IndlelaData.co.za   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   return this;
}
