// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("Index.html", "Indlela Group", "Contact Us  Indlela Group is working closely with some of the world’s best manufacturing companies and keeping our clients up to date with latest and best innovative technologies, committed to evolving daily production and securing your future    Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  Indlela Communications is Company that focuses on Telecommunications and Data Services Workingon Wireless and Fibre networks and integrating these networks into voice and data services stretching over the howl of South Africa Indlela Communication   Communicating the way forward     Indlela Data is a ICT Company Focusing on complex IT systems integration  and Print Management and was the cornerstone for Indlela Group of companies  Indlela Finance is our Financial Muscle and with Indlela Finance we will make sure that your dreams will become reality by financing your dream to make sure tomorrow becomes today  Entabeni Security is a company that give complex security solutions from Access Control to physical Security we will protect your assets and give you that well deserved sleep at night knowing you are safe and sound  Company info needed  Indlela property is managing all of the Indlela Groups Properties from Renting Warehouses to giving you a well-deserved break at one of our guesthouses  Company info needed  Company info needed  Online Store   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Log-a-Call.html", "Indlela Group Call Log", "Copyright © 2020 BuddySoft Systems  Share  Contact Us  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  If you have a Fault to report please continue with this form   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Risk.html", "Indlela Group Risk", "Contact Us  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  Copyright © 2020 BuddySoft Systems   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Construction.html", "Indlela Group Construction", "Projects  Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  To be the benchmark supplier of services on the African Continent by using our consultancy methodology and addressing key critical issues that are burdening the business bottom line   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Amend-debt.html", "Indlela Group Debt Collectors", "Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Communications.html", "Indlela Group Communications", "Contact Us  Indlela Group is working closely with some of the world’s best manufacturing companies and keeping our clients up to date with latest and best innovative technologies, committed to evolving daily production and securing your future    Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  NWET is an ICT company which strives for increased customer relations and work satisfaction Better industry service with leading technical knowledge to provide customers with the best known solution for their business practice  View More  Coverage Map  Full Network Setup and Maintenance   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Online-Store.html", "Indlela Group Online Store", "Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Security.html", "Indlela Group Security", "Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Finance.html", "Indlela Group Finance", "Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com  T&C Apply All Loans and Rentals Are Subject to approval   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   this[database_length++] = new SearchPage("Property.html", "Indlela Group Property", "Contact Us  Copyright © 2020 BuddySoft Systems  Share  Indlela Group & Indlela Data  Pty  Ltd  14 Gould Street Wilkoppies Klerkdsdorp 2751  018 462 1256  info@indlelagroup.com  https //indlelagroup.com   ", "ICT Solutions  Construction  Housing  Debt Collectors  Security  Communications   NWET  Finance  Risk");
   return this;
}
